import { useRouter } from 'next/router'
import React, { useEffect, useRef, useState } from 'react'
import Button from "@material-tailwind/react/Button";
import Tooltips from "@material-tailwind/react/Tooltips";
import TooltipsContent from "@material-tailwind/react/TooltipsContent";
import { RiAddCircleLine } from "react-icons/ri";
import Head from 'next/head';
import QuantityItem from '../../components/QuantityItem';
import { useDispatch, useSelector } from 'react-redux';
import { addItemToCart } from '../../features/cart/cartSlice';
export default function Product() {
  const buttonRef = useRef();
  const route = useRouter()
  const [data, setData] = useState()
  useEffect(() => {
    fetch(`http://localhost:3000/api/products/${route.query.id}`)
      .then(res => res.json())
      .then((data) => setData(data))
  }, [])
  const [quantity, setQuantity]=useState(1)
  const dispatch=useDispatch()
  const cartItems=useSelector(state=>state.cart.cartItems)
  console.log(cartItems);
  return (
    <div>
      <Head>
        <title>RB Shopping | products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        data && (
          <div className='container mx-auto my-48 mb-80 flex'>
            <div className='w-1/2'>
              <img src={data.src} className='w-full h-96' />
            </div>
            <div className='mx-10 text-white flex flex-col justify-center'>
              <p className='text-3xl'>{data.title}</p>
              <p className='my-10'>{data.body}</p>
              <p className='text-red-500 font-bold'>{data.price}</p>
              <div className='flex justify-between items-center mt-10'>
                <QuantityItem quantity={quantity} setQuantity={setQuantity} />
                <Button color="lightBlue" ref={buttonRef} ripple="light">
                  <p className='text-2xl' onClick={()=>dispatch(addItemToCart({'product':data, 'quantity':quantity}))}><RiAddCircleLine /></p>
                </Button>
                <Tooltips placement="left" ref={buttonRef}>
                  <TooltipsContent>Add to Cart</TooltipsContent>
                </Tooltips>
              </div>
            </div>
          </div>
        )
      }
    </div>
  )
}
