import Head from 'next/head'
import React from 'react'

export default function about() {
  return (
    <div>
        <Head>
        <title>RB Shopping | about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      About
    </div>
  )
}
