import Head from 'next/head'
import React from 'react'

export default function contacts() {
    return (
        <div>
            <Head>
                <title>RB Shopping | contacts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            Contacts
        </div>
    )
}
