import Head from 'next/head'
import Home from '../components/Home'
import 'material-icons/iconfont/material-icons.css';
export default function index() {
  return (
    <div>
      <Head>
        <title>RB Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Home />
      </main>
    </div>
  )
}
